services:
  db:
    image: postgres:14.1
    restart: always
    container_name: notifeye_db_dev
    env_file: .envrc
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_HOST: ${DB_HOST:-localhost}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - /var/lib/postgresql/data
